name: Trigger on Draft Release Creation

on:
  release:
    types: [unpublished]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if it's a draft release
        run: echo "This is a draft release!"
